name: scrnaseq-oa
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - r-base=4.3
  - r-essentials
  - r-seurat
  - r-ggplot2
  - r-dplyr
  - r-readr
  - r-tidyr
  - r-purrr
  - r-stringr
  - r-yaml
  - r-optparse
  - r-patchwork
  - r-data.table
  - r-pheatmap
  - r-openxlsx
  - r-remotes
  - bioconductor-singlecellexperiment
  - bioconductor-scater
  - bioconductor-scran
  - bioconductor-fgsea
  - bioconductor-clusterprofiler
  - bioconductor-org.Hs.eg.db
  - bioconductor-msigdbr
  - gcc            # 某些包需要编译
  - git
