name: scrna-oa
channels:
  - conda-forge
  - bioconda
  - defaults

dependencies:
  - r-base=4.5.1
  - r-essentials
  - r-seurat=5.0.1
  - r-seuratobject
  - r-ggplot2
  - r-dplyr
  - r-readr
  - r-tidyr
  - r-purrr
  - r-stringr
  - r-pheatmap
  - r-optparse
  - r-reshape2
  - r-openxlsx
  - r-data.table
  - r-gsva
  - bioconductor-gseabase
  - bioconductor-clusterprofiler
  - bioconductor-org.hs.eg.db
  - bioconductor-msigdbr
  - bioconductor-singlecellexperiment
  - bioconductor-scater
  - bioconductor-scran
  - r-yaml
  - r-remotes
  - r-devtools
  - git
  - wget
  - python=3.10
  - snakemake=7.32
